apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: app-argo-application
  namespace: argocd
spec:
  project: default

  source:
    repoURL: https://github.com/BENMALEKarim/cloud-native-demo.git
    targetRevision: HEAD
    path: app
  destination:
    server: https://kubernetes.default.svc
    namespace: app

  syncPolicy:
    syncOptions:
    - CreateNamespace=true

    automated:
      selfHeal: true
      prune: true